### DISCUSSION TITLE
Is a page transition working incorrect in document-driven mode?

### DISCUSSION THREAD

**Discussion by olegfedak** [nuxt/content#1391] [Q&A]
I have installed fresh [document driven project](https://github.com/nuxt/content/tree/main/examples/essentials/document-driven) without pages folder. So, page transition works like this:

https://user-images.githubusercontent.com/5526547/181390555-a5ccd20c-4206-42ba-9601-8638e7dd1e8c.mov

After adding pages folder and [...slug].vue there, page transitions work fine

**Comment by nobkd** [comment]
I did'nt have these problems, but I have 2 suggestions:

You can try
* removing `<NuxtLayout>` from your `app.vue`
* using  `npx nuxi init doc-driven-app -t doc-driven` from https://github.com/nuxt/starter as alternative starting point

**Reply by olegfedak** [reply]
Unfortunatly, the same! 
I've just added styles only into app.vue:
```css
.page-enter-active,
.page-leave-active {
  transition: opacity 0.5s ease;
}
.page-enter,
.page-leave-to {
  opacity: 0;
} 
```
