### DISCUSSION TITLE
Search YAML object inside an array

### DISCUSSION THREAD

**Discussion by giticon** [nuxt/content#2590] [General]
Is there a way to search documents, with something similar to :

```javascript
 .where({ hashtag: { $contains: route.params.slug[0] } })
```

using a list of object inside an array?

```YAML
hashtag:
  - web-design: web design
  - graphic design: graphic design
  - developer: developer
```
