### DISCUSSION TITLE
YAML synatx in md

### DISCUSSION THREAD

**Discussion by brokuka** [nuxt/content#2971] [Q&A]
Let's say we have some data like this:

```
::gear2
---
id: imperial-boots
name: Imperial Boots
slot: boots
rarity: epic
statsProgression:
  heroDefense:
    values:
      - 40
      - 50
      - 60
      - 80
      - 100
      - 120
      - 140
      - 160
      - 179
    extra:
      '100': '100'

---
::
```

in all yaml to js online service it will transfers as expect, but in md files

`'100': '100'` make array of index `100`, how to prevent that? Need to make object instead of array.
