### ISSUE TITLE
Navigating between two routes not working correctly, work only on full page reload

### ISSUE THREAD

**Issue by leamsigc** [nuxt/content#1366]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.5.0`
- Nuxt Version:     `3.0.0-rc.6-27638947.92269dd`
- Package Manager:  `npm@8.4.1`
- Builder:          `vite`
- User Config:      `ssr`, `target`, `nitro`, `modules`, `experimental`, `unocss`, `colorMode`, `content`, `unlighthouse`, `schemaOrg`
- Runtime Modules:  `@vueuse/nuxt@8.9.4`, `@unocss/nuxt@0.44.5`, `@pinia/nuxt@0.3.0`, `@nuxtjs/color-mode@3.1.4`, `@nuxt/content@2.1.0-27638985.cbf08ad`, `@unlighthouse/nuxt@0.3.29`, `nuxt-schema-org@0.7.0-beta.3`, `@nuxt/image-edge@1.0.0-27628766.3629b9a`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/github/leamsigc/wetzlar-giessen-devs-meetup?file=README.md

### Describe the bug

- Go from / to /about back to /
- Will generate error in the console and the content is not updated 

```sh

TypeError: can't access property "parentNode", e is null

ncaught (in promise) TypeError: h is null
```

Vercel deploy https://wetzlar-giessen-devs-meetup.vercel.app

### Additional context

Preview https://wetzlar-giessen-devs-meetup.vercel.app/

### Logs

```shell
TypeError: can't access property "parentNode", e is null

ncaught (in promise) TypeError: h is null
```

**Comment by farnabaz** [comment]
Thanks for the issue and reproduction. This will fix in #1370.

Also just to mention, you should update `head.meta` values in `about.md`:

```
head:
    htmlAttrs:
        lang: 'en'
    bodyAttrs:
        class: ''
    meta:
        - name: 'keywords' 
          content: 'Giessen  and Wetzlar developer meetup group'
        - name: 'robots'
          content: 'index, follow'    
        - name: 'author'      
          content: 'Leamsigc'
```
