### ISSUE TITLE
include array of strings property name in fullTextSearchFields

### ISSUE THREAD

**Issue by josh-hemphill** [nuxt/content#178]
### Is your feature request related to a problem? Please describe.
Currently, the `fullTextSearchFields` configuration can only take fields that are a string, however a common use case for full text search is to also include your tags.

### Describe the solution you'd like
Having a configuration like this:
```yaml
title: Testing title
description: |
  Some testing text, 
  That also happens to be multi-line
tags: [test, example, placeholder]
summary: some text
```
And then be able to include the tags in your search, especially if field weighting is added too.

```js
content: {
	// Only search in title and description
	fullTextSearchFields: ['title', 'tags', 'description', 'summary'],
},
```

### Describe alternatives you've considered
I've looked at storing all the tags in a string and splitting on spaces, but not being able to use spaces would limit the usefulness of the tags in search. Using other characters to delineate the individual tags is working, but having it stored in an array would be very useful.
