### ISSUE TITLE
How to find YAML documents by value from an array inside them?

### ISSUE THREAD

**Issue by afuno** [nuxt/content#2191]
### Discussed in https://github.com/nuxt/content/discussions/2172

<div type='discussions-op-text'>

<sup>Originally posted by **afuno** July 13, 2023</sup>
There are documents in YAML format that have the following data inside:

```yml
title: Test
slug: test

# ...

bands:
  - slug: band-1
    active: true
  - slug: band-2
    active: true

# ...
```

Can you please tell me what condition should be written in `where` to get documents for `slug` with value `band-2`?

There is currently no such example in the documentation. The example for categories is different and doesn't fit.
</div>
