### ISSUE TITLE
fetchContentNavigation() option, to fetch additional variables from pages

### ISSUE THREAD

**Issue by davision** [nuxt/content#2467]
`fetchContentNavigation()` method now works really great, but for some cases it really lack additional data to build navigation with let say, an icon or a description. Currently, the returned object only consists of page `title` and `_path`. I see that title is already fetched from the page header section.

Would it be cool, if the page have such header:
```yaml
---
title: About Us
description: This is about us page
icon: mdi:account-group
---
```

And then when calling fetchContentNavigation(), I would have this extra info in the object as well:

```js
[
  {
    "title": "About Us",
    "_path": "/about",
    "description": "This is about us page",
    "icon": "mdi:account-group"
  }
]
```

Or is there any other existing way to achieve this?
