### ISSUE TITLE
How to render Prism line-numbers

### ISSUE THREAD

**Issue by Yiddishe-Kop** [nuxt/content#28]
Regarding [codeblocks](https://content.nuxtjs.org/writing#codeblocks) - how do I use the Prism line-numbers plugin to render the line-numbers.

I tried making a plugin in the plugins folder like so:
```js
import 'prismjs/plugins/line-numbers/prism-line-numbers'
```
But it doesn't work.

**Comment by benjamincanac** [comment]
Hey @Yiddishe-Kop,

Nuxt Content highlight markdown codeblocks on the server-side and store it as JSON AST but also add the css of Prism in your app automatically.

However, you can also apply Prism on the client-side by using `Prism.highlightAll()` for example:

```js
import Prism from 'prismjs'
import 'prismjs/plugins/line-numbers/prism-line-numbers.js'

export default {
    // ...
    mounted () {
        Prism.highlightAll()
    }
    // ...
}
```

And add the css to your page: (example taken from the [Prism.js documentation](https://prismjs.com/plugins/line-numbers/))

```css
pre[class*="language-"].line-numbers {
  position: relative;
  padding-left: 3.8em;
  counter-reset: linenumber;
}

pre[class*="language-"].line-numbers > code {
  position: relative;
  white-space: inherit;
}

.line-numbers .line-numbers-rows {
  position: absolute;
  pointer-events: none;
  top: 0;
  font-size: 100%;
  left: -3.8em;
  width: 3em; /* works for line-numbers below 1000 lines */
  letter-spacing: -1px;
  border-right: 1px solid #999;

  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}

.line-numbers-rows > span {
  display: block;
  counter-increment: linenumber;
}

.line-numbers-rows > span:before {
  content: counter(linenumber);
  color: #999;
  display: block;
  padding-right: 0.8em;
  text-align: right;
}
```
