### ISSUE TITLE
[Nuxt Studio] Support Bun In Github pages Studio Deployment.

### ISSUE THREAD

**Issue by oxgen1** [nuxt/content#3084]
## `studio-nuxt-build` job fails using a project using bun.
Fails on Step install pnpm with error: 
```Error: No pnpm version is specified. Please specify it by one of the following ways: - in the GitHub Action config with the key "version" - in the package.json with the key "packageManager"```

------------------------------
- Operating System: Linux
- Node Version:     v20.18.1
- Nuxt Version:     3.15.4
- CLI Version:      3.21.1
- Nitro Version:    2.10.4
- Package Manager:  bun@1.1.8
- Builder:          -
- User Config:      compatibilityDate, devtools, css, postcss, content, modules
- Runtime Modules:  @nuxt/content@3.1.0
- Build Modules:    -
------------------------------

Attached is the worker log 
At the very least if this cannot be supported it should be able to fallback to pnpm without failure.

[studio-nuxt-build-job-logs.txt](https://github.com/user-attachments/files/18648041/studio-nuxt-build-job-logs.txt)

## Bun Supports Github actions
Support for Bun Github actions here: https://bun.sh/guides/runtime/cicd

## This feature is straightforward to support two Issues Prevent This from working
1. The pkgman step fails to detect Bun as a package manager.
This can be done easily by adding this statment into the run command ```[ -f "./bun.lockb" ] && echo "bun"```

2. Bun removes the requirement for setup-node. as setup-node cache does not support Bun. 

## Below is my workaround. 
*Note: I have no experience with Github Actions if you are experience and know a better way please mention it* 

```

name: studio-nuxt-build
run-name: studio nuxt build

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Add write workflow permissions
permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: .

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Identify package manager
        id: pkgman
        run: |
          cache=`[ -f "./pnpm-lock.yaml" ] && echo "pnpm" || ([ -f "./bun.lockb" ] && echo "bun" || ([ -f "./package-lock.json" ] && echo "npm" || ([ -f "./yarn.lock" ] && echo "yarn" || echo "")))`
          package_manager=`[ ! -z "$cache" ] && echo "$cache" || echo "pnpm"`
          echo "cache=$cache" >> $GITHUB_OUTPUT
          echo "package_manager=$package_manager" >> $GITHUB_OUTPUT
      - uses: pnpm/action-setup@v4
        if: ${{ steps.pkgman.outputs.package_manager == 'pnpm' }}
        name: Install pnpm
        id: pnpm-install

      - uses: oven-sh/setup-bun@v2
        if: ${{ steps.pkgman.outputs.package_manager == 'bun' }}
        name: Install pnpm
        id: bun-install

      - uses: actions/setup-node@v4
        if: ${{ steps.pkgman.outputs.package_manager != 'bun' }}
        with:
          version: ${{ matrix.node }}
          cache: ${{ steps.pkgman.outputs.cache }}

      - name: Install dependencies
        run: ${{ steps.pkgman.outputs.package_manager }} install

      - name: Generate
        if: ${{ steps.pkgman.outputs.package_manager != 'bun' }}
        run: npx nuxi build --preset github_pages
        env:
          NUXT_CONTENT_PREVIEW_API: https://api.nuxt.studio

      - name: Generate
        if: ${{ steps.pkgman.outputs.package_manager == 'bun' }}
        run: bun run nuxi build --preset github_pages
        env:
          NUXT_CONTENT_PREVIEW_API: https://api.nuxt.studio
          

      # Deployment job
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./.output/public
```
