### ISSUE TITLE
Getting 'Could not parse config.transforms[index] is not a function' and nuxt content cannot get md file data

### ISSUE THREAD

**Issue by shash7** [nuxt/content#747]
### Version
@nuxt/content: v1.12.0
nuxt: 2.14.12

### Reproduction Link
Not sure how to reproduce this. I'm working on a Windows laptop, on a relatively fresh Nuxt build. I'm setting up @nuxt/content and for some reason, fetch() returns an empty array and console thows a warning message about parsing.

### What is Expected?
fetch() should return data of the md files.

### What is actually happening?
fetch() is not returning any data. Even the api endpoint for testing is not showing any data.

**Comment by shash7** [comment]
Update - .json files work fine. Its only the .md files having parsing troubles.

**Comment by shash7** [comment]
Sure:

```
---
title: A test blog post
date: 2021-01-28T10:56:20.061Z
description: test description
---

Test body
```

I tried a few other variants of the .md file but no dice.

![Frame 62](https://user-images.githubusercontent.com/3054413/106759553-feb72b80-6686-11eb-922e-b9f4541f2bdd.jpg)

**Comment by manwithafox** [comment]
Get the same since this morning.
No nuxt.js. Culprit seems to be an updated remark/unified@9.2.0 in my case.
Are you using this as well?

**Comment by manwithafox** [comment]
More specific mdast-util-from-markdown@0.6.2

**Comment by shash7** [comment]
@manwithafox yep that's correct. Reverting to 1.11.1 solves this issue.

**Comment by shash7** [comment]
@benjamincanac I haven't tried with 1.13.1

**Comment by kurukururuu** [comment]
+1 getting the same error. any update on this? Thanks~

**Comment by MoodyBones** [comment]
I'm getting a similar error with  "@nuxt/content": "^1.14.0" and `.yml` files coming from NetlifyCMS. I think the bug is coming from nuxt/content and not Netlify CMS.

**"Could not parse ./content/companies/hero.yml: expected a single document in the stream, but found more"** 
and array returned = 0

I'm trying to set up Netlify CMS on top of nuxt/content. I'm following this doc https://www.netlifycms.org/docs/nuxt/ 
"The important thing to note is the **format: 'frontmatter'** value on each collection. This is important for consuming content in Nuxt with the nuxt/content module."

`config.yml`
```
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: 'Companies'
    name: 'companies'
    format: 'frontmatter'
    files:
      - label: 'Hero'
        name: 'hero'
        file: 'content/companies/hero.yml'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - { label: Button, name: button, widget: string }
          - { label: Link, name: link, widget: string }
      - label: 'Logos'
        name: 'logos'
        file: 'content/companies/logos.yml'
        fields:
          - { label: Title, name: title, widget: string }
          - label: Logos
            name: logos
            widget: list
            max: 6
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Image, name: image, widget: image }
      - label: 'Shortlist'
        name: 'shortlist'
        file: 'content/companies/shortlist.yml'
        fields:
          - { label: Title, name: title, widget: string }
          - label: Steps
            name: steps
            widget: list
            max: 4
            fields:
              - { label: Title, name: title, widget: string }
      - label: 'How it works'
        name: 'how'
        file: 'content/companies/how.yml'
        fields:
          - label: About
            name: about
            widget: list
            max: 4
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Intro, name: intro, widget: markdown }
              - { label: Image, name: image, widget: image }
              - { label: 'Image alt', name: alt, widget: string }
```

`hero.yml`
```
---
title: The simplest way to build a powerful junior sales team ;)
intro: Get access to young, qualified & job-seeking sales juniors
button: start building your sales team
link: https://hyretalents.com/
---
```

I got the netlifyCMS config/communication working ok, the error occurs as soon as I add nuxt/content and try and fetch the data. 

`returns 0`
```
  async asyncData({ $content, params }) {
    const article = await $content('companies').fetch()
    return {
      article,
    }
  },
```

frontmatter saves the files as `.yml`. I will have a play-around and try to change it to `.json` and report back.

Has anyone got a Nuxt/NetlifyCMS working example to share? I've worked with Gridsome/NetlifyCMS in the past, and that uses GraphQL for the queries. I'm new to Nuxt and writing these kinds of queries, I'm not sure if it's me or a bug :)
