### ISSUE TITLE
Fetch using Where by filtering array of objects

### ISSUE THREAD

**Issue by ManasMadrecha** [nuxt/content#800]
We (@madrecha) are building our local language dictionary using Nuxt Content. 
I wish to filter the fetching of my posts (i.e., words).

I have data like this in each md file:

```
---
url:
  title: foo (in our local language)
  transliteration: bar
  slugurl: foo-bar

meanings:
  - meaning: first meaning of this word heart
    examples: abc
    synonyms: xyz
  - meaning: second meaning of this word
 ---

## Noun
### Meaning
(some component to show above meanings in beautiful way)

```

I want to limit my fetch from 1000s of all words.

Using `nestedProperties` option in Content in nuxt-config file, I could then use `url.title` in `where`.

```
async fetch() {
  this.words = await $this.content("words")
                     .where({'url.title': {$contains: 'foo'}})
                     .fetch();
 }
```

However, I am unable to filter `meanings` array with `meaning`.
I tried adding `meanings[0].meaning`, `meanings[1].meaning`, etc. in `nestedProperties`, but that does not work in `where`.

Using any permutation of all LokiDB query examples, is there any way to even fetch using `meanings` in `where`?

For example, something like this:
```
async fetch() {
  this.words = await this.$content("words")
        .where({
          $or: [
            { "url.title": { $contains: "foo" } },
            { "meanings[0].meaning": { $contains: "heart" } },
          ],
        })
        .fetch();
 }

or 
          .where( { meanings: { $containsAny: { meaning: { $contains: "heart" } } } })

```

`$contains` only works for an array if that array is full of only simple values, so I cannot use it directly for `meanings` array, which is an array of objects.

Also, $regix can be used to search for array of strings.

Is there any operator to filter array of objects in Loki js?
