### ISSUE TITLE
The updatedAt field of all the contents are changed on deployment.

### ISSUE THREAD

**Issue by TunNandaAung** [nuxt/content#913]
When deploying a static site to **netlify** or **vercel**, the `updatedAt` field of all the contents are changed to the deployment time.
You can see in this [example nuxt blog repository](https://github.com/nuxtlabs/demo-blog-nuxt-content) that the repo was last update on **Jan 7** and the `updatedAt` field of the contents on the [website](https://blog-with-nuxt-content.netlify.app/) are **Jan 7** as well. This behavior also happens on latest version (**v1.14.0**).

### Steps to reproduce
- Clone this [repository](https://github.com/nuxtlabs/demo-blog-nuxt-content).
- Deploy it on netlify or vercel.

**Comment by JoseeWouters** [comment]
I noticed the same for the `createdAt` date, which caused my pagination to go from 1 to 3 to 2. And in my RSS feed happened the same, (generating the feed with the [Nuxt Feed module](https://github.com/nuxt-community/feed-module).

**Comment by LukaHarambasic** [comment]
I also was confused about this, but for me, it makes sense as during the build steps the files are copied/moved/recreated at the servers of netlify/vercel. To fix this, I added the attribute `publishedAt` and set the date manually.

**Comment by mrleblanc101** [comment]
I seem to have the same issue using GitHub Pages (with Github Actions).
Am I missing something ? Why doesn't it use the Git timestamp instead of the operating system created_at ?

With `nuxt dev`, the one with the missing image is last.
<img width="1912" alt="Capture d’écran, le 2022-07-11 à 01 31 57" src="https://user-images.githubusercontent.com/17392251/178195410-86685b0e-c2b5-4f43-b10b-7719ff839659.png">
On GitHub Pages, the one with a missing image is in the middle:
<img width="1912" alt="Capture d’écran, le 2022-07-11 à 01 31 58" src="https://user-images.githubusercontent.com/17392251/178195452-de21328f-5092-4620-b309-280b79e65da7.png">

With `nuxt dev`
file 1: `"createdAt": "2022-06-23T03:57:36.719Z"`
file 2: `"createdAt": "2022-06-23T04:17:49.584Z"`
file 3: `"createdAt": "2022-07-11T01:15:46.009Z"`

On GitHub Pages:
file 1: `"createdAt": "2022-07-11T05:20:28.319Z"`
file 2: `"createdAt": "2022-07-11T05:20:28.319Z"`
file 3: `"createdAt": "2022-07-11T05:20:28.319Z"`

Here is my GitHub Action workflow it it helps, maybe I did something wrong:
```yaml
name: ci

on:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master

jobs:
    ci:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [14]

        steps:
            - name: Checkout 🛎
              uses: actions/checkout@master

            - name: Setup node env 🏗
              uses: actions/setup-node@v2.1.5
              with:
                  node-version: ${{ matrix.node }}
                  check-latest: true

            - name: Cache node_modules 📦
              uses: actions/cache@v2.1.4
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install dependencies 👨🏻‍💻
              run: npm ci --prefer-offline --no-audit

            - name: Build Static
              run: npm run generate

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
```
